name: Course API Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'course-api/**'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Build and push to quay.io registry
        environment: dev
        uses: sclorg/build-and-push-action@v2
        working-directory: course-api
        with:
          registry: ${{ env.ACR_URL }}
          registry_namespace: ${{ env.ACR_NAMESPACE }}
          registry_username: ${{ secrets.ACR_USERNAME }}
          registry_token: ${{ secrets.ACR_PASSWORD }}
          dockerfile: "Dockerfile"
          image_name: ""
          tag: "tag"
          archs: "amd64, s390x"