openapi: 3.0.1
info:
  title: Course API
  version: 1.0.0
  description: API for retrieving course information
paths:
  /courses:
    get:
      summary: Get list of courses
      description: Retrieve a list of all courses
      responses:
        '200':
          description: A list of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
components:
  schemas:
    Course:
      type: object
      properties:
        _id:
          type: string
          example: '1'
        name:
          type: string
          example: 'INFO 6150'
        instructor:
          type: string
          example: 'Amuthan'
        location:
          type: object
          properties:
            room:
              type: string
              example: '102'
            building:
              type: string
              example: 'Shillman'
        schedule:
          type: object
          properties:
            startTime:
              type: string
              example: 'Wed 6:10 PM'
            endTime:
              type: string
              example: 'Wed 9:40 PM'