name: Course Search API Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'course-api/**'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    environment: dev
    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      
      - name: Set up working directory
        run: |
          pwd 
          cd course-api; 
          pwd

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: 'ACR Login'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Build and push image'
        run: |
          docker build . -t ${{ vars.ACR_URL }}/coursesearchapi:${{ github.sha }} -t${{ vars.ACR_URL }}/coursesearchapi:latest
          docker image push --all-tags ${{ vars.ACR_URL }}/coursesearchapi
      
      - name: 'Logout via Azure CLI'
        run: |
          az logout